import { Item, Molecule } from '@/lib/types';
import { zeroAddress } from 'viem';

const MOCKED_MOLECULES: Molecule[] = [
  {
    identifier: 'ing-1',
    name: 'Ju₃',
    giving_atoms: [],
    receiving_atoms: [],
    bond: {
      strength: 0,
      type: 'none',
    },
    activation_energy: 0,
    radius: 0,
    electrical_conductivity: 0,
    thermal_conductivity: 0,
    toughness: 0,
    hardness: 0,
    ductility: 0,
  },
  {
    identifier: 'ing-2',
    name: 'TiN',
    giving_atoms: [],
    receiving_atoms: [],
    bond: {
      strength: 0,
      type: 'none',
    },
    activation_energy: 0,
    radius: 0,
    electrical_conductivity: 0,
    thermal_conductivity: 0,
    toughness: 0,
    hardness: 0,
    ductility: 0,
  },
  {
    identifier: 'ing-3',
    name: 'TiC',
    giving_atoms: [],
    receiving_atoms: [],
    bond: {
      strength: 0,
      type: 'none',
    },
    activation_energy: 0,
    radius: 0,
    electrical_conductivity: 0,
    thermal_conductivity: 0,
    toughness: 0,
    hardness: 0,
    ductility: 0,
  },
  {
    identifier: 'ing-4',
    name: 'WAf₂',
    giving_atoms: [],
    receiving_atoms: [],
    bond: {
      strength: 0,
      type: 'none',
    },
    activation_energy: 0,
    radius: 0,
    electrical_conductivity: 0,
    thermal_conductivity: 0,
    toughness: 0,
    hardness: 0,
    ductility: 0,
  },
  {
    identifier: 'ing-5',
    name: 'Fe₃C',
    giving_atoms: [],
    receiving_atoms: [],
    bond: {
      strength: 0,
      type: 'none',
    },
    activation_energy: 0,
    radius: 0,
    electrical_conductivity: 0,
    thermal_conductivity: 0,
    toughness: 0,
    hardness: 0,
    ductility: 0,
  },
  {
    identifier: 'ing-6',
    name: 'SiO₂',
    giving_atoms: [],
    receiving_atoms: [],
    bond: {
      strength: 0,
      type: 'none',
    },
    activation_energy: 0,
    radius: 0,
    electrical_conductivity: 0,
    thermal_conductivity: 0,
    toughness: 0,
    hardness: 0,
    ductility: 0,
  },
  {
    identifier: 'ing-7',
    name: 'Al₂O₃',
    giving_atoms: [],
    receiving_atoms: [],
    bond: {
      strength: 0,
      type: 'none',
    },
    activation_energy: 0,
    radius: 0,
    electrical_conductivity: 0,
    thermal_conductivity: 0,
    toughness: 0,
    hardness: 0,
    ductility: 0,
  },
  {
    identifier: 'ing-8',
    name: 'Cu',
    giving_atoms: [],
    receiving_atoms: [],
    bond: {
      strength: 0,
      type: 'none',
    },
    activation_energy: 0,
    radius: 0,
    electrical_conductivity: 0,
    thermal_conductivity: 0,
    toughness: 0,
    hardness: 0,
    ductility: 0,
  },
  {
    identifier: 'ing-9',
    name: 'Ag',
    giving_atoms: [],
    receiving_atoms: [],
    bond: {
      strength: 0,
      type: 'none',
    },
    activation_energy: 0,
    radius: 0,
    electrical_conductivity: 0,
    thermal_conductivity: 0,
    toughness: 0,
    hardness: 0,
    ductility: 0,
  },
  {
    identifier: 'ing-10',
    name: 'CuAg',
    giving_atoms: [],
    receiving_atoms: [],
    bond: {
      strength: 0,
      type: 'none',
    },
    activation_energy: 0,
    radius: 0,
    electrical_conductivity: 0,
    thermal_conductivity: 0,
    toughness: 0,
    hardness: 0,
    ductility: 0,
  },
];

export const MOCKED_CRAFTABLE_ITEMS: Item[] = [
  {
    id: 'item-1',
    name: 'Diamond Pickaxe',
    description: 'An extremely hard and durable pickaxe',
    creator: zeroAddress,
    defaultImageUri: '',
    type: 'non-fungible',
    traits: [
      { name: 'power', value: '42.9' },
      { name: 'conductivity', value: '0.1' },
      { name: 'toughness', value: '1.82' },
      { name: 'speed', value: '0.5' },
    ],
    blueprint: [
      { element: MOCKED_MOLECULES[0], amount: 1 },
      { element: MOCKED_MOLECULES[1], amount: 1 },
      { element: MOCKED_MOLECULES[2], amount: 1 },
    ],
  },
  {
    id: 'item-2',
    name: 'Tungsten Blade',
    description: 'A sharp blade with high thermal conductivity',
    creator: zeroAddress,
    defaultImageUri: '',
    type: 'fungible',
    traits: [
      { name: 'power', value: '36.815' },
      { name: 'conductivity', value: '0.0' },
      { name: 'toughness', value: '0.95' },
      { name: 'speed', value: '1.2' },
    ],
    blueprint: [
      { element: MOCKED_MOLECULES[3], amount: 1 },
      { element: MOCKED_MOLECULES[4], amount: 1 },
    ],
  },
  {
    id: 'item-3',
    name: 'Crystal Shield',
    description: 'A transparent shield with high durability',
    creator: zeroAddress,
    defaultImageUri: '',
    type: 'fungible',
    traits: [
      { name: 'power', value: '28.9' },
      { name: 'conductivity', value: '0.12' },
      { name: 'toughness', value: '1.25' },
      { name: 'speed', value: '0.3' },
    ],
    blueprint: [
      { element: MOCKED_MOLECULES[5], amount: 1 },
      { element: MOCKED_MOLECULES[6], amount: 1 },
    ],
  },
  {
    id: 'item-4',
    name: 'Conductive Wire',
    description: 'A flexible wire with excellent electrical conductivity',
    creator: zeroAddress,
    defaultImageUri: '',
    type: 'fungible',
    traits: [
      { name: 'power', value: '22.3' },
      { name: 'conductivity', value: '0.95' },
      { name: 'toughness', value: '0.75' },
      { name: 'speed', value: '0.8' },
    ],
    blueprint: [
      { element: MOCKED_MOLECULES[7], amount: 1 },
      { element: MOCKED_MOLECULES[8], amount: 1 },
      { element: MOCKED_MOLECULES[9], amount: 1 },
    ],
  },
];

export const MOCKED_OWNED_ITEMS: Item[] = [
  {
    id: 'item-1',
    name: 'Diamond Pickaxe',
    description: 'An extremely hard and durable pickaxe',
    creator: zeroAddress,
    defaultImageUri: '',
    type: 'non-fungible',
    traits: [
      { name: 'power', value: '42.9' },
      { name: 'conductivity', value: '0.1' },
      { name: 'toughness', value: '1.82' },
      { name: 'speed', value: '0.5' },
    ],
    blueprint: [
      { element: MOCKED_MOLECULES[0], amount: 1 },
      { element: MOCKED_MOLECULES[1], amount: 1 },
      { element: MOCKED_MOLECULES[2], amount: 1 },
    ],
  },
];
